env:
  - COVERAGE=true
language: ruby
rvm:
  - 2.6.1
services: mongodb
notifications:
  email:
    - didier@nocoffee.fr
before_install:
  - gem install bundler
branches:
  except:
    - gh-pages
sudo: required
